export const SET_NAME = 'SET_NAME'
export const ADD_STAFF = 'ADD_STAFF'
export const GET_ALL_STAFFS = 'GET_ALL_STAFFS'
export const UPDATE_STAFF = 'UPDATE_STAFF'
export const DELETE_STAFF = 'DELETE_STAFF'
